from schemas import BaseResponse

class ResponseConstant:
    SUCCESS = BaseResponse(ResponseCode="00", ResponseMessage="Completed successfully")
    REFER_TO_CARD_ISSUER = BaseResponse(ResponseCode="01", ResponseMessage="Refer to card issuer")
    REFER_TO_CARD_ISSUERS_SPECIAL_CONDITIONS = BaseResponse(ResponseCode="02", ResponseMessage="Refer to card issuer's special conditions")
    INVALID_MERCHANT = BaseResponse(ResponseCode="03", ResponseMessage="Invalid merchant")
    PICK_UP = BaseResponse(ResponseCode="04", ResponseMessage="Pick-up")
    DO_NOT_HONOR = BaseResponse(ResponseCode="05", ResponseMessage="Do not honor")
    PICK_UP_CARD_SPECIAL_CONDITION = BaseResponse(ResponseCode="07", ResponseMessage="Pick-up card, special condition")
    HONOUR_WITH_IDENTIFICATION = BaseResponse(ResponseCode="08", ResponseMessage="Honour with identification")
    REQUEST_IN_PROGRESS = BaseResponse(ResponseCode="09", ResponseMessage="Request in progress")
    APPROVED_FOR_PARTIAL_AMOUNT = BaseResponse(ResponseCode="10", ResponseMessage="Approved for partial amount")
    APPROVED_VIP = BaseResponse(ResponseCode="11", ResponseMessage="Approved (VIP)")
    INVALID_TRANSACTION = BaseResponse(ResponseCode="12", ResponseMessage="Invalid transaction")
    INVALID_AMOUNT = BaseResponse(ResponseCode="13", ResponseMessage="Invalid amount")
    INVALID_CARD_NUMBER_NO_SUCH_NUMBER = BaseResponse(ResponseCode="14", ResponseMessage="Invalid card number (no such number)")
    NO_SUCH_ISSUER = BaseResponse(ResponseCode="15", ResponseMessage="No such issuer")
    APPROVED_UPDATE_TRACK_3 = BaseResponse(ResponseCode="16", ResponseMessage="Approved, update track 3")
    CUSTOMER_CANCELLATION = BaseResponse(ResponseCode="17", ResponseMessage="Customer cancellation")
    CUSTOMER_DISPUTE = BaseResponse(ResponseCode="18", ResponseMessage="Customer dispute")
    RE_ENTER_TRANSACTION = BaseResponse(ResponseCode="19", ResponseMessage="Re-enter transaction")
    INVALID_RESPONSE = BaseResponse(ResponseCode="20", ResponseMessage="Invalid response")
    NO_ACTION_TAKEN = BaseResponse(ResponseCode="21", ResponseMessage="No action taken")
    SUSPECTED_MALFUNCTION = BaseResponse(ResponseCode="22", ResponseMessage="Something Went Wrong")
    UNACCEPTABLE_TRANSACTION_FEE = BaseResponse(ResponseCode="23", ResponseMessage="Unacceptable transaction fee")
    FILE_UPDATE_NOT_SUPPORTED_BY_RECEIVER = BaseResponse(ResponseCode="24", ResponseMessage="File update not supported by receiver")
    UNABLE_TO_LOCATE_RECORD = BaseResponse(ResponseCode="25", ResponseMessage="Unable to locate record")
    DUPLICATE_RECORD = BaseResponse(ResponseCode="26", ResponseMessage="Duplicate record")
    FILE_UPDATE_FIELD_EDIT_ERROR = BaseResponse(ResponseCode="27", ResponseMessage="File update field edit error")
    FILE_UPDATE_FILE_LOCKED_OUT = BaseResponse(ResponseCode="28", ResponseMessage="File update file locked out")
    FILE_UPDATE_NOT_SUCCESSFUL_CONTACT_ACQUIRER = BaseResponse(ResponseCode="29", ResponseMessage="File update not successful, contact acquirer")
    FORMAT_ERROR = BaseResponse(ResponseCode="30", ResponseMessage="Format error")
    BANK_NOT_SUPPORTED_BY_SWITCH = BaseResponse(ResponseCode="31", ResponseMessage="Bank not supported by switch")
    COMPLETED_PARTIALLY = BaseResponse(ResponseCode="32", ResponseMessage="Completed partially")
    EXPIRED_CARD = BaseResponse(ResponseCode="33", ResponseMessage="Expired card")
    SUSPECTED_FRAUD = BaseResponse(ResponseCode="34", ResponseMessage="Suspected fraud")
    CARD_ACCEPTOR_CONTACT_ACQUIRER = BaseResponse(ResponseCode="35", ResponseMessage="Card acceptor contact acquirer")
    RESTRICTED_CARD = BaseResponse(ResponseCode="36", ResponseMessage="Restricted card")
    CARD_ACCEPTOR_CALL_ACQUIRER_SECURITY = BaseResponse(ResponseCode="37", ResponseMessage="Card acceptor call acquirer security")
    ALLOWABLE_PIN_TRIES_EXCEEDED = BaseResponse(ResponseCode="38", ResponseMessage="Allowable PIN tries exceeded")
    NO_CREDIT_ACCOUNT = BaseResponse(ResponseCode="39", ResponseMessage="No credit account")
    REQUESTED_FUNCTION_NOT_SUPPORTED = BaseResponse(ResponseCode="40", ResponseMessage="Requested function not supported")
    LOST_CARD = BaseResponse(ResponseCode="41", ResponseMessage="Lost card")
    NO_UNIVERSAL_ACCOUNT = BaseResponse(ResponseCode="42", ResponseMessage="No universal account")
    STOLEN_CARD_PICK_UP = BaseResponse(ResponseCode="43", ResponseMessage="Stolen card, pick-up")
    NO_INVESTMENT_ACCOUNT = BaseResponse(ResponseCode="44", ResponseMessage="No investment account")
    NOT_SUFFICIENT_FUNDS = BaseResponse(ResponseCode="51", ResponseMessage="Not sufficient funds")
    NO_CHECKING_ACCOUNT = BaseResponse(ResponseCode="52", ResponseMessage="No checking account")
    NO_SAVINGS_ACCOUNT = BaseResponse(ResponseCode="53", ResponseMessage="No savings account")
    INCORRECT_PERSONAL_IDENTIFICATION_NUMBER = BaseResponse(ResponseCode="55", ResponseMessage="Incorrect personal identification number")
    NO_CARD_RECORD = BaseResponse(ResponseCode="56", ResponseMessage="No card record")
    TRANSACTION_NOT_PERMITTED_TO_CARDHOLDER = BaseResponse(ResponseCode="57", ResponseMessage="Transaction not permitted to cardholder")
    TRANSACTION_NOT_PERMITTED_TO_TERMINAL = BaseResponse(ResponseCode="58", ResponseMessage="Transaction not permitted to terminal")
    EXCEEDS_WITHDRAWAL_AMOUNT_LIMIT = BaseResponse(ResponseCode="61", ResponseMessage="Exceeds withdrawal amount limit")
    SECURITY_VIOLATION = BaseResponse(ResponseCode="63", ResponseMessage="Security violation")
    ORIGINAL_AMOUNT_INCORRECT = BaseResponse(ResponseCode="64", ResponseMessage="Original amount incorrect")
    EXCEEDS_WITHDRAWAL_FREQUENCY_LIMIT = BaseResponse(ResponseCode="65", ResponseMessage="Exceeds withdrawal frequency limit")
    CARD_ACCEPTOR_CALL_ACQUIRERS_SECURITY_DEPARTMENT = BaseResponse(ResponseCode="66", ResponseMessage="Card acceptor call acquirer's security department")
    HARD_CAPTURE_REQUIRES_THAT_CARD_BE_PICKED_UP_AT_ATM = BaseResponse(ResponseCode="67", ResponseMessage="Hard capture (requires that card be picked up at ATM)")
    RESPONSE_RECEIVED_TOO_LATE = BaseResponse(ResponseCode="68", ResponseMessage="Response received too late")
    ALLOWABLE_NUMBER_OF_PIN_TRIES_EXCEEDED = BaseResponse(ResponseCode="75", ResponseMessage="Allowable number of PIN tries exceeded")
    INVALID_CREDIT_ACCOUNT = BaseResponse(ResponseCode="76", ResponseMessage="Invalid Credit Account")
    INVALID_DEBIT_ACCOUNT = BaseResponse(ResponseCode="77", ResponseMessage="Invalid Debit Account")
    INVALID_ACCOUNT = BaseResponse(ResponseCode="78", ResponseMessage="Invalid Account")
    INVALID_ENTRY = BaseResponse(ResponseCode="79", ResponseMessage="Invalid Entry")
    AUTHORIZATION_KEY_MUST_BE_PASSED = BaseResponse(ResponseCode="80", ResponseMessage="Authorization Key must be passed")
    INVALID_ACTION = BaseResponse(ResponseCode="81", ResponseMessage="Invalid Action")
    ACCOUNT_DELETED = BaseResponse(ResponseCode="82", ResponseMessage="Your account has been deleted or suspended")
    ERROR_INVALID_DATE_FORMAT = BaseResponse(ResponseCode="83", ResponseMessage="Invalid date Format")
    ERROR_INVALID_PATH = BaseResponse(ResponseCode="84", ResponseMessage="Invalid Path")
    FAILED_TO_PERFORM_ACTION = BaseResponse(ResponseCode="85", ResponseMessage="Failed to perform action")
    ERROR_INVALID_CREDENTIAL = BaseResponse(ResponseCode="86", ResponseMessage="Invalid Credential")
    ERROR_ACTIVITY_ALREADY_QUEUED = BaseResponse(ResponseCode="87", ResponseMessage="Activity Already Queued Authorized")
    ERROR_ACTIVITY_ALREADY_PERFORMED = BaseResponse(ResponseCode="87", ResponseMessage="Activity Already Performed")
    SUCCESS_ACTIVITY_QUEUE = BaseResponse(ResponseCode="00", ResponseMessage="Activity Queued Awaiting Authorization")
    FAILED_TO_CREATE_RECORD = BaseResponse(ResponseCode="88", ResponseMessage="d")
    FAILED_TO_UPDATE_RECORD = BaseResponse(ResponseCode="89", ResponseMessage="Failed to update record")
    CUTOFF_IS_IN_PROCESS = BaseResponse(ResponseCode="90", ResponseMessage="Cutoff is in process")
    TRANSACTION_CAN_BE_SENT_AGAIN_IN_A_FEW_MINUTES = BaseResponse(ResponseCode="", ResponseMessage="(switch ending a day's business and starting the next. Transaction can be sent again in a few minutes)")
    ISSUER_OR_SWITCH_IS_INOPERATIVE = BaseResponse(ResponseCode="91", ResponseMessage="Issuer or switch is inoperative")
    FINANCIAL_INSTITUTION_OR_INTERMEDIATE_NETWORK_FACILITY_CANNOT_BE_FOUND_FOR_ROUTING = BaseResponse(ResponseCode="92", ResponseMessage="Financial institution or intermediate network facility cannot be found for routing")
    TRANSACTION_CANNOT_BE_COMPLETED_VIOLATION_OF_LAW = BaseResponse(ResponseCode="93", ResponseMessage="Transaction cannot be completed. Violation of law")
    DUPLICATE_TRANSMISSION = BaseResponse(ResponseCode="94", ResponseMessage="Duplicate transmission")
    RECONCILE_ERROR = BaseResponse(ResponseCode="95", ResponseMessage="Reconcile error")
    SYSTEM_MALFUNCTION = BaseResponse(ResponseCode="22", ResponseMessage="System malfunction")
    SUCCESS_UPLOAD_SUBMITTED = BaseResponse(ResponseCode="97", ResponseMessage="Failed to upload records.")
    ERROR_NO_PENDING_ENTRIES = BaseResponse(ResponseCode="98", ResponseMessage="No Pending Entries.")
    ERROR_INVALID_BANK_CODE = BaseResponse(ResponseCode="99", ResponseMessage="Invalid Bank Code")
    ERROR_AUTHENTICATION_FAILED = BaseResponse(ResponseCode="100", ResponseMessage="Authentication Failed")
    ERROR_FAILED_TO_GENERATE_OTP = BaseResponse(ResponseCode="101", ResponseMessage="Failed to generate OTP")
    ERROR_INVALID_TYPE = BaseResponse(ResponseCode="102", ResponseMessage="Invalid Type")
    ERROR_INVALID_INTEREST_RATE = BaseResponse(ResponseCode="103", ResponseMessage="Invalid interest Rate")
    ERROR_INVALID_CHECKER_ID = BaseResponse(ResponseCode="104", ResponseMessage="Invalid Checker ID")
